platform :ios, '9.0'
inhibit_all_warnings!

target 'PLShortVideoKitDemo' do
   pod 'PLShortVideoKit'
   pod 'Fabric', '1.6.11'
   pod 'Crashlytics', '3.8.4'
   pod 'Masonry', '1.0.2'
   pod 'FLAnimatedImage', '1.0.12'
   pod 'Nama', '6.1.0'
end
